# Generated by Django 3.1 on 2021-04-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharexcare', '0003_auto_20210411_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
